### ISSUE TITLE
Forgotten password POST request is not returning Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by DMCTowns** [jdudmesh/justthetalk-api#1]
Reset password via the UI is failing with a CORS error on the POST request.

OPTIONS is setting the header:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization,Content-Type
Access-Control-Allow-Methods: PUT,POST,GET,DELETE,OPTIONS
Access-Control-Allow-Origin: https://beta.justthetalk.com
Connection: keep-alive
Content-Length: 0
Content-Type: application/json; charset=utf-8
Date: Tue, 06 Dec 2022 09:25:56 GMT
Keep-Alive: timeout=60
Server: nginx/1.19.10
Vary: Origin
```

Whereas POST is not:
```
Connection: keep-alive
Content-Length: 36
Content-Type: text/plain; charset=utf-8
Date: Tue, 06 Dec 2022 09:25:56 GMT
Server: nginx/1.19.10
```

I've had a look at **UserHandler.ForgotPassword** which calls **utils.AnonymousHandlerFunction** which in turn calls **utils.HandlerFunction** which sets 
`res.Header().Set(HeaderAccessControlAllowOrigin, req.Header.Get("Origin"))`

Which looks like it __should__ work, but clearly isn't. Any pointers?

**Comment by jdudmesh** [comment]
Odd. I saw a 500 error relating to a missing db column. I've now added the missing columns and it seems to be working now. Can you retest.

**Comment by DMCTowns** [comment]
That's fixed the issue - however when I follow the link, I get the following:

Application error: a client-side exception has occurred (see the browser console for more information).

And in the console:

```
framework-2191d16384373197bc0a.js:1 ReferenceError: credentials is not defined
    at _app-d8c9c7c2ffc4a9fb16a1.js:1:85846
    at _app-d8c9c7c2ffc4a9fb16a1.js:1:26760
    at resetpassword-aed87097092ab394085a.js:1:5032
    at Ii (framework-2191d16384373197bc0a.js:1:105590)
    at t.unstable_runWithPriority (framework-2191d16384373197bc0a.js:1:130375)
    at Wl (framework-2191d16384373197bc0a.js:1:45761)
    at Oi (framework-2191d16384373197bc0a.js:1:105051)
    at vi (framework-2191d16384373197bc0a.js:1:96508)
    at framework-2191d16384373197bc0a.js:1:45984
    at t.unstable_runWithPriority (framework-2191d16384373197bc0a.js:1:130375)
uu @ framework-2191d16384373197bc0a.js:1
main-89e612c37cd79392e22d.js:1 ReferenceError: credentials is not defined
    at _app-d8c9c7c2ffc4a9fb16a1.js:1:85846
    at _app-d8c9c7c2ffc4a9fb16a1.js:1:26760
    at resetpassword-aed87097092ab394085a.js:1:5032
    at Ii (framework-2191d16384373197bc0a.js:1:105590)
    at t.unstable_runWithPriority (framework-2191d16384373197bc0a.js:1:130375)
    at Wl (framework-2191d16384373197bc0a.js:1:45761)
    at Oi (framework-2191d16384373197bc0a.js:1:105051)
    at vi (framework-2191d16384373197bc0a.js:1:96508)
    at framework-2191d16384373197bc0a.js:1:45984
    at t.unstable_runWithPriority (framework-2191d16384373197bc0a.js:1:130375)
le @ main-89e612c37cd79392e22d.js:1
main-89e612c37cd79392e22d.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
le @ main-89e612c37cd79392e22d.js:1
api.justthetalk.com/user/refresh-token:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
```

Looks like Request POST: https://api.justthetalk.com/user/refresh-token is returning a 400 Bad Request:
`{"message":"Bad request","status":400}
`

**Comment by jdudmesh** [comment]
Checked front end and backend code. Looking better now.

**Comment by DMCTowns** [comment]
Yep, all good now. Thanks, @jdudmesh
